### ISSUE TITLE
Typo in HistContext registration

### ISSUE THREAD

**Issue by emyoulation** [kajmikkelsen/HistContext#1]
There's a typo in the registration.

It is now missing a comma at the end of the new `help_url` line.

It works when I added the comma. Thanks for removing the diagnostic prints to the console.

**Comment by kajmikkelsen** [comment]
Yeah I had fixed it, but only on my private copy.
My only excuse is that I have a heavy anxiety for dentists, and suddenly I had to get a tooth pulled out.
So I am in a state of panic and high on drugs and has been so for a couple of days.
Thanks

**Comment by emyoulation** [comment]
Missing Comma has been added and Black formatting applied to the Gramps Plugin Registration file.
