### ISSUE TITLE
use GEDCOM date instead of FROM/TO

### ISSUE THREAD

**Issue by hartenthaler** [kajmikkelsen/HistContext#7]
I suggest to use a GEDCOM date range like

`FROM 1 JAN 1801 TO 15 FEB 1840`

instead of the two columns FROM and TO in the csv file. That would allow to use other calendar systems (eg. Julian, Hebrew, ...), too.

**Comment by kajmikkelsen** [comment]
I don't agree. A mix of reserved words and delimited fields should be avoid.
Using gramps date formats, will be consistent with the rest of the gramps software.

**Comment by hartenthaler** [comment]
Ok, but using gramps date formats will you not allow to enter dates in another calendar system. This excludes Hewbrew or Islamic users and prevents entering dates of historic events before the Gregorian calendar was established.
