### ISSUE TITLE
Use of wikidata instead of / additionally to URL in csv file

### ISSUE THREAD

**Issue by hartenthaler** [kajmikkelsen/HistContext#8]
I suggest using a link to wikidata like
`https://www.wikidata.org/wiki/Q12214`
instead of or additional to the URL in the csv file like
`https://wikipedia.org/wiki/Smallpox`

That would allow linking directly to Wikipedia in the language of the user. If the user is using the German language, the link can be directed using the information in wikidata () to the german Wikipedia article:
`https://de.wikipedia.org/wiki/Pocken`

**Comment by kajmikkelsen** [comment]
If I recall correct, I already changed so the local wiki would be used, according to @emyoulation

**Comment by hartenthaler** [comment]
Have you tested that? When I click on your link https://wikipedia.org/wiki/Smallpox the English Wikipedia opens instead of the German Wikipedia. How should Wikipedia know that an article in English Wikipedia about "smallpox" is related to an article about "Pocken" on German Wikipedia? It does not work that way.

It should be possible to implement such a function using the information in wikidata, but I have not done that.

**Comment by emyoulation** [comment]
It only works for articles that wikipedia cross-refernces in different languages.

It works sometimes. But using the `en.` subdomain precludes wikipedia EVER adapting to the OS language.
